apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgsql
  namespace: openshift-gitops
spec:
  destination:
    namespace: mediawiki-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: pgsql-manifest
    repoURL: 'https://github.com/kishorpc/gitops-repo.git'
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
	syncOptions:
    - CreateNamespace=true  
	  
