apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mediawiki
    app.kubernetes.io/component: mediawiki
    app.kubernetes.io/instance: mediawiki
    app.kubernetes.io/name: php
  name: mediawiki
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: mediawiki
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        deployment: mediawiki
    spec:
      volumes:
        - name: pgsql-storage
          persistentVolumeClaim:
            claimName: pgsql-pv-claim
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/mediawiki-gitops/mediawiki
        imagePullPolicy: IfNotPresent
        name: mediawiki
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        volumeMounts:
            - name: pgsql-storage
              mountPath: /var/lib/mediawiki/data
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
