apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mediawikihpa
spec:
  maxReplicas: 3
  metrics:
  - resource:
      name: memory
      target:
        averageValue: 400Mi
        type: AverageValue
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mediawiki
