apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: mediawiki
    app.kubernetes.io/component: mediawiki
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/name: php
  name: mediawiki
spec:
  host: mediawiki.kishor-gitops-poc-ba8e38d4c011d627379af1a4280c4e35-0000.us-south.containers.appdomain.cloud
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: mediawiki
    weight: 100
  wildcardPolicy: None
